spring:
  profiles:
    active: p4000
  application:
    name: order-service
server:
  servlet:
    context-path: /api
feign:
  circuitebreaker:
    enable: true
#  hystrix:
#    enabled: true
  client:
    config:
      default:
        readTimeout: 1000
---
spring:
  profiles: p4000
server:
  port: 4000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/,http://localhost:1100/eureka/